### ISSUE TITLE
Article: Don't be Dogmatic! Be Agile and Pragmatic!

### ISSUE THREAD

**Issue by bruderol** [Zuehlke/fifty-shades#31]
Be aware to not follow stupidly any dogmatic `set of rules` without thinking well about consequences or even doing it in a way it was never meant like (e.g. overdoing it, exagerating the original meaning or even using those dogmas to not having to discuss and argument anymore ...)

Some examples of such rules that do more harm than any good if followed just blindly and in a dogmatic way or done without thinking about its consequences or maybe even doing it in a way it was never meant:   

* "working software over comprehensive documentation" (aka "not write any documentation")   
* "follow git flow branching strategy with feature branches" (and not integrating continuously - @peitor ;-) )
* "the blog I read about Page Object pattern says never to put assertions into Page Objects" (so we should NEVER do that! Dont even think about it! And let's immediately refactor all our tests accordingly!)
* "do not write ANY source code comments! We write Clean Code instead - POINT"
* "Abstractions should not depend on details. Details should depend on abstractions." --> so dont ever create an instance of a class directly, always only depend on interfaces.
* "do not automate any e2e/UI tests - because the test pyramid says that we should just focus on the lower level of the pyramids and e2e/UI tests are slow and fragile anyway - so let's not loose time with such things and instead write only fine granular unit tests and those should only cover one class and always mock ALL the other collaborators - like I learned it in that cool blog I read about unit testing!" (there are very good arguments for UI/E2E tests and many advantages over unit tests and the pyramid was probably not meant to say: WRITE NONE!)
   
And please do not get me wrong: I like Agile Manifesto, Git Flow Branching Model, Feature Branches, Martin Fowler in general and even his article about Page Object Pattern. As well I like Clean Code, SOLID Design Principles and TDD using Unit-Tests - those are all practices I appreciate a lot and that influenced my way of thinking and working - but still all of this things have a lot of danger inside, if just following them stupidly and in a very dogmatic way.

This could also make a good introduction, because that might be important to be aware of when reading any other advice in the articles of our book. And it is also a general good philosophy and spirit for project work. I think this spirit should be something that we take care of throughout the book, to well define in each article in what context something is meant and where also the limitations or disadvantages or even dangers or pitfalls of each approach/idea are.

Following yammer thread and especially the comments by @damphyr inspired me, to write something about that: https://www.yammer.com/zuehlke.com/#/Threads/show?threadId=832088152
--> "Sterile, mechanic "rules" to be followed more or less religiously as if somehow you can substitute critical thinking and adaptive methods"
@damphyr Thanks! 

So this should be a pleading for we have less to fight against such dogmas and all try to be open and think well about how to do something in a project instead of following blindly any rule set and causing troubles with this to the project or our colleagues.

**Comment by bruderol** [comment]
By the way: I am well aware that this is a big challenge for all of us to not fall into that "dogma" trap - I have fallen into that trap many times as well and have to fight every day to not fall into it.

**Comment by adiherzog** [comment]
In 2001 a part of the software testing community created "The Seven Basic Principles of the Context-Driven School" (see http://context-driven-testing.com/). It was the same year when the agile manifesto was created. Despite the good intentions of the agile manifesto back then I think that it happens too often that people fall into the dogmatic trap by just following out-of-the-box agile methodologies.

Therefore I think it might be better to talk about "Context Driven Software Development" instead. I know, it's another buzzword. But it's an anti-buzzword at heart, as it mainly just says: There's no best practice. The more experience and the more tools you have in your toolbox the more likely you are going to find a well suited solution for the problem at hand. So keep learning and become really an expert in what you do.

I had the idea of "Context Driven Software Development" on the last day of the three-day "Rapid Software Testing" Course with James Bach and Michael Bolton beginning of March. Another important takeaway from the course is that they talk a lot about "heuristics" instead of "rules" (https://en.wikipedia.org/wiki/Heuristic). This slight change of language can have a huge impact on how we think about stuff. We can think of heuristics as "rules of thumb" that give us guidance when we need to make a decision. But at the same time the word implies that it's not a perfect solution and that we might think of an even better solution in the given context.

In the end, it's important that we as professionals can explain ourselves about why we do things like we do them. And just saying that methodology X or my old friend Y says it's good to do something is not a very strong argument.

**Comment by adiherzog** [comment]
Ah, and you could use this quote as an introduction or in the end (I don't know where I got it from...).

"When two smart people disagree, one of them is probably missing some context."

https://twitter.com/adi_herzog/status/799803597491998725

**Comment by bruderol** [comment]
@adiherzog Yes, those are as well some good points. Thank you!
I will have to see what of all of these ideas fits into that one article.

"Heuristic" sounds to mee to academic. I rather try to use the term "guide" instead of "guideline" or "rule", cause that says what it should be: some "guidance" into right direction, without stopping to think whether it makes sense in some context, and not strictly to follow rules, if you have good reasons to do it differently. 

I especially like your idea of "Context Driven Software Development", that could make up a good 2nd article in the book, and I could at least link to this idea in this article here. And I also think that the quote you were mentioning would rather make a good introduction to that other article.

**Comment by bruderol** [comment]
had some funny nerdy discussion yesterday with some colleagues about "dont use static methods!" versus "static is great, make everything static first!" - somehow reminds me of this topic here. ;-)
